### ISSUE TITLE
CSS build errors on fresh clone

### ISSUE THREAD

**Issue by xandout** [swimmadude66/AngularPWASeed#6] opened 2019-12-05 04:11 UTC
**System Details**
OS: Fedora
Node: v10.16.3
NPM: 6.9.0

```
npm run dev

> angularpwaseed@8.2.4 predev /root/source-code/homeschool/back/AngularPWASeed
> rimraf dist


> angularpwaseed@8.2.4 dev /root/source-code/homeschool/back/AngularPWASeed
> gulp watch

[03:56:35] Using gulpfile ~/source-code/homeschool/back/AngularPWASeed/gulpfile.js
[03:56:35] Starting 'watch'...
[03:56:35] Starting 'watchWebpack'...
[03:56:35] Starting 'compileNode'...
(node:11092) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
[03:56:40] Finished 'compileNode' after 5.33 s
[03:56:40] Starting 'startServer'...
[03:56:40] Finished 'startServer' after 17 ms
[03:56:40] Starting 'watchServer'...
Watching files for changes...
Debugger listening on ws://127.0.0.1:5858/711b030d-8944-43dc-98f0-219f042f56db
For help, see: https://nodejs.org/en/docs/inspector
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/NormalModule.js:313:20)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at VirtualFileSystemDecorator.readFile (/root/source-code/homeschool/back/AngularPWASeed/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:42:13)
    at processResource (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at runLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/NormalModule.js:313:20)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at childCompiler.runAsChild (/root/source-code/homeschool/back/AngularPWASeed/node_modules/mini-css-extract-plugin/dist/loader.js:135:14)
    at compile (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/Compiler.js:343:11)
    at hooks.afterCompile.callAsync.err (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/Compiler.js:671:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/source-code/homeschool/back/AngularPWASeed/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/root/source-code/homeschool/back/AngularPWASeed/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/Compiler.js:668:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/source-code/homeschool/back/AngularPWASeed/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/source-code/homeschool/back/AngularPWASeed/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/Compilation.js:1385:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/source-code/homeschool/back/AngularPWASeed/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/source-code/homeschool/back/AngularPWASeed/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/Compilation.js:1376:32) '\n'
webpack-internal:///1:1
throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.\n - options has an unknown property 'includePaths'. These properties are valid:\n   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }\n    at validate (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)\n    at Object.loader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/dist/index.js:36:28)");//# sourceURL=[module]
^

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/dist/index.js:36:28)
    at eval (webpack-internal:///1:1:7)
    at Object.<anonymous> (/root/source-code/homeschool/back/AngularPWASeed/src/client/components/inputgroup/styles.scss:97:1)
    at __webpack_require__ (/root/source-code/homeschool/back/AngularPWASeed/src/client/components/inputgroup/styles.scss:20:30)
    at eval (webpack-internal:///0:2:22)
    at Object.<anonymous> (/root/source-code/homeschool/back/AngularPWASeed/src/client/components/inputgroup/styles.scss:91:1)
    at __webpack_require__ (/root/source-code/homeschool/back/AngularPWASeed/src/client/components/inputgroup/styles.scss:20:30)
    at /root/source-code/homeschool/back/AngularPWASeed/src/client/components/inputgroup/styles.scss:84:18
    at /root/source-code/homeschool/back/AngularPWASeed/src/client/components/inputgroup/styles.scss:87:10
    at Script.runInContext (vm.js:133:20)
    at Script.runInNewContext (vm.js:139:17) '\n'
Hash: 252ea0c9e72997b7f50e
Version: webpack 4.39.3
Time: 5639ms
Built at: 12/05/2019 3:56:41 AM
                                                          Asset       Size  Chunks             Chunk Names
                         .well-known/apple-app-site-association   79 bytes          [emitted]  
                                    .well-known/assetlinks.json    3 bytes          [emitted]  
                                app.3f8a1ee75de510b70e39.min.js   1.18 KiB       0  [emitted]  app
                        assets/icons/android-chrome-192x192.png   2.36 KiB          [emitted]  
                        assets/icons/android-chrome-512x512.png    6.3 KiB          [emitted]  
          assets/icons/apple-touch-icon-120x120-precomposed.png   1.23 KiB          [emitted]  
                      assets/icons/apple-touch-icon-120x120.png  971 bytes          [emitted]  
          assets/icons/apple-touch-icon-152x152-precomposed.png   1.49 KiB          [emitted]  
                      assets/icons/apple-touch-icon-152x152.png   1.19 KiB          [emitted]  
          assets/icons/apple-touch-icon-180x180-precomposed.png   1.75 KiB          [emitted]  
                      assets/icons/apple-touch-icon-180x180.png   1.25 KiB          [emitted]  
            assets/icons/apple-touch-icon-60x60-precomposed.png  770 bytes          [emitted]  
                        assets/icons/apple-touch-icon-60x60.png  535 bytes          [emitted]  
            assets/icons/apple-touch-icon-76x76-precomposed.png  867 bytes          [emitted]  
                        assets/icons/apple-touch-icon-76x76.png  631 bytes          [emitted]  
                  assets/icons/apple-touch-icon-precomposed.png   1.75 KiB          [emitted]  
                              assets/icons/apple-touch-icon.png   1.25 KiB          [emitted]  
                                 assets/icons/browserconfig.xml  259 bytes          [emitted]  
                                     assets/icons/demo_icon.svg   1.17 KiB          [emitted]  
                                 assets/icons/favicon-16x16.png  424 bytes          [emitted]  
                                 assets/icons/favicon-32x32.png  651 bytes          [emitted]  
                                       assets/icons/favicon.ico   14.7 KiB          [emitted]  
                                assets/icons/mstile-144x144.png   1.88 KiB          [emitted]  
                                assets/icons/mstile-150x150.png   1.57 KiB          [emitted]  
                                assets/icons/mstile-310x150.png   1.69 KiB          [emitted]  
                                assets/icons/mstile-310x310.png   3.14 KiB          [emitted]  
                                  assets/icons/mstile-70x70.png   1.37 KiB          [emitted]  
                             assets/icons/safari-pinned-tab.svg   1.99 KiB          [emitted]  
                                      assets/images/check-o.svg  226 bytes          [emitted]  
                                        assets/images/empty.png  156 bytes          [emitted]  
                                    assets/images/logo-flat.svg  792 bytes          [emitted]  
                                          assets/images/x-o.svg  656 bytes          [emitted]  
                                                     index.html   2.31 KiB          [emitted]  
                                                  manifest.json  628 bytes          [emitted]  
                          polyfills.d0664b44653c0ca0d928.min.js   1.18 KiB       1  [emitted]  polyfills
                                                     robots.txt   38 bytes          [emitted]  
                             styles.5a234e88bca7c0251f5e.min.js   3.88 KiB       2  [emitted]  styles
                                                          sw.js   3.93 KiB          [emitted]  
wb-assets/precache-manifest.5244826c29b2115cffaa52bb29aa6d1e.js   1.11 KiB          [emitted]  
Entrypoint app = app.3f8a1ee75de510b70e39.min.js
Entrypoint polyfills = polyfills.d0664b44653c0ca0d928.min.js
Entrypoint styles = styles.5a234e88bca7c0251f5e.min.js
[0] ./src/client/main.ts 0 bytes {0} [built]
[1] ./src/client/polyfills.ts 0 bytes {1} [built]
[2] ./src/client/scss/styles.scss 2.7 KiB {2} [built] [failed] [1 error]

WARNING in app.3f8a1ee75de510b70e39.min.js contains invalid source map

WARNING in polyfills.d0664b44653c0ca0d928.min.js contains invalid source map

WARNING in styles.5a234e88bca7c0251f5e.min.js contains invalid source map

ERROR in ./src/client/scss/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/webpack/lib/NormalModule.js:313:20)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at VirtualFileSystemDecorator.readFile (/root/source-code/homeschool/back/AngularPWASeed/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:42:13)
    at processResource (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/loader-runner/lib/loadLoader.js:47:3)

ERROR in Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'includePaths'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/dist/index.js:36:28)
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  9.94 KiB       0  
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/client/index.html 2.3 KiB {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/postcss-loader/src/index.js??postcss!node_modules/sass-loader/dist/cjs.js??ref--6-3!src/client/scss/styles.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./src/client/scss/styles.scss 650 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./src/client/scss/styles.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./src/client/scss/styles.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
     - options has an unknown property 'includePaths'. These properties are valid:
       object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
        at validate (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
        at Object.loader (/root/source-code/homeschool/back/AngularPWASeed/node_modules/sass-loader/dist/index.js:36:28)
[03:56:41] Finished 'watchWebpack' after 5.77 s
[ master ]: App starting on port 3000
[ master ]: Spinning up 7 workers
Debugger listening on ws://127.0.0.1:5859/7ad4ad08-b2fe-4bba-a4cb-bc8b0f571e17
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:5860/770bca9b-7d0f-4776-bce8-6d43f1d250c9
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:5861/29bf3d67-d55e-47b6-9e65-6ef894324373
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:5862/f8f2f700-073e-44e7-8f99-9be3b8d1264d
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:5863/f3d1b0cb-43e7-4e13-81ea-9c54c477671f
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:5865/1d227a3c-29d5-4ffd-94ee-d2b415060f0a
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:5864/03d8e9bb-6c50-4f3f-b260-991614df7d54
For help, see: https://nodejs.org/en/docs/inspector
[Browsersync] Proxying: http://localhost:3000
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3001
    External: http://192.168.0.71:3001
 -------------------------------------
          UI: http://localhost:3003
 UI External: http://localhost:3003
 -------------------------------------
[ worker 1 ]: Ready and listening!
[ worker 2 ]: Ready and listening!
[ worker 3 ]: Ready and listening!
[ worker 7 ]: Ready and listening!
[ worker 5 ]: Ready and listening!
[ worker 4 ]: Ready and listening!
[ worker 6 ]: Ready and listening!
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
[ worker 1 ]: ::ffff:127.0.0.1 - GET / HTTP/1.1 200 2362 - 7.008 ms
[ worker 2 ]: ::ffff:127.0.0.1 - GET /app.3f8a1ee75de510b70e39.min.js HTTP/1.1 200 - - 6.783 ms
[ worker 3 ]: ::ffff:127.0.0.1 - GET /assets/icons/favicon.ico HTTP/1.1 200 - - 7.014 ms
[ worker 7 ]: ::ffff:127.0.0.1 - GET / HTTP/1.1 200 2362 - 6.859 ms
[ worker 5 ]: ::ffff:127.0.0.1 - GET /app.3f8a1ee75de510b70e39.min.js HTTP/1.1 200 - - 6.919 ms
[ worker 4 ]: ::ffff:127.0.0.1 - GET /assets/icons/favicon.ico HTTP/1.1 200 - - 6.881 ms
[ worker 6 ]: ::ffff:192.168.0.35 - GET / HTTP/1.1 200 - - 6.989 ms
```

**Comment by localyost3000** [comment] 2020-02-12 20:38
I am not sure how I missed this being open for so long. I apologize for the wait! The issue comes from a change to an underlying dependency of a dependency, but I have the workaround in a local branch. I will push up a fix for it tonight.

On another note, if you'd like to run 1 thread for the backend for easier debugging, you can set your environment var `MAX_WORKERS` to 1. If you are using a headless environment (as the BrowserSync logs suggest) you can also set `DOCKER_MODE` to true or 1, and that will prevent it from trying to open your browser

**Comment by localyost3000** [comment] 2020-02-13 01:51
fixed in master now. In case you run in to this in other projects, the issue is `sass-loader` changing its options object by moving most keys into a `sassOptions` child object.

**Closed as completed by localyost3000** 2020-02-13 01:51 UTC
